# baseURL = 'https://glowing-kashata-66e40c.netlify.app/' 
baseURL = "http://localhost:1313/"

languageCode = 'en-us'
theme = "netlify-basic"
canonifyURLs = true

[[menu.main]]
    name = "FAQ"
    url = "/faq/"

[params]
  logo = "img/collagenico_logo.svg"
  cta_button_title = "zamawiam"

  [[params.benefits]]
    title = "Potwierdzona efektywność"
    image = "/img/header_benefit_1.svg"
    
  [[params.benefits]]
    title = "Produkt Roku 2023"
    image = "/img/benefit_prize.svg"

  [[params.benefits]]
    title = "W 100% naturalne składniki"
    image = "/img/header_benefit_3.svg"

   [params.footer]
     [[params.footer.column]]
     title = "Collagenico"
       list = [
        { linkTitle = "Jak to działa?", url = "jak-to-dziala" },
        { linkTitle = "Składniki", url = "skladniki" },
        { linkTitle = "Opinie", url = "opinie" },
        { linkTitle = "Referencje naukowe", url = "referencje-naukowe" }
       ]
    [[params.footer.column]]
    title = "POMOC"
    list = [
      { linkTitle = "FAQ", url = "faq" },
      { linkTitle = "Kontakt", url = "kontakt" },
      { linkTitle = "Regulamin", url = "terms/regulamin" },
      { linkTitle = "Polityka zwrotów", url = "polityka-zwrotow" }
    ]
     [[params.footer.column]]
     title = "INFORMACJE"
      list = [
       { linkTitle = "Polityka prywatności", url = "polityka-prywatnosci"},
       { linkTitle = "Warunki Korzystania", url = "warunki-korzystania"},
       { linkTitle = "Zarządzanie Zgodami", url = "zarządzanie zgodami"},
       { linkTitle = "Jawność Informacji", url = "jawnosc-informacji"}
      ]
  