languageCode = 'en-us'
theme = "netlify-basic"
baseURL = "https://collagenico24.net/"
defaultContentLanguage = 'pl'
defaultContentLanguageInSubdir = true
canonifyURLs = true
  
[module]
  [[module.mounts]]
    source = "themes/netlify-basic/node_modules"
    target = "static/libs/node_modules"

[languages]
  [languages.pl]
  contentDir = 'content/pl'
  languageCode = 'pl'
  languageDirection = 'ltr'
  languageName = 'Polski'
  title = 'Collagenico - Advanced Collagen Supplement for Hair Growth and Skin Rejuvenation'
  weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"

[params]
  baseURL = "http://localhost:1313/"

  logo = "img/collagenico_logo.svg"
  cta_button_title = "zamawiam"

  [[params.benefits]]
    title = "Potwierdzona efektywność"
    image = "/img/header_benefit_1.svg"
    
  [[params.benefits]]
    title = "Produkt Roku 2023"
    image = "/img/benefit_prize.svg"

  [[params.benefits]]
    title = "W 100% naturalne składniki"
    image = "/img/header_benefit_3.svg"

   [params.footer]
     [[params.footer.column]]
     title = "Collagenico"
       list = [
        { linkTitle = "Jak to działa?", url = "pl/#how" },
        { linkTitle = "Składniki", url = "pl/#ingredients" },
        { linkTitle = "Opinie", url = "pl/#opinions" },
        { linkTitle = "Referencje naukowe", url = "pl/#references" }
       ]
    [[params.footer.column]]
    title = "POMOC"
    list = [
      { linkTitle = "FAQ", url = "pl/faq" },
      { linkTitle = "Kontakt", url = "pl/contact" },
      { linkTitle = "Regulamin", url = "pl/terms/terms-of-service" },
      { linkTitle = "Polityka zwrotów", url = "pl/terms/returns-policy" }
    ]
     [[params.footer.column]]
     title = "INFORMACJE"
      list = [
       { linkTitle = "Polityka prywatności", url = "pl/terms/privacy-policy"},
       { linkTitle = "Zarządzanie Zgodami", url = "pl/terms/consent-management"},
       { linkTitle = "Jawność Informacji", url = "pl/terms/disclosure"}
      ]
